FROM centos:6

MAINTAINER "Apache CloudStack" <dev@cloudstack.apache.org>

ENV PKG_URL=http://jenkins.buildacloud.org/job/package-rhel63-master-noredist/lastSuccessfulBuild/artifact/dist/rpmbuild/RPMS/x86_64

RUN yum install -y \
    ${PKG_URL}/cloudstack-common-4.6.0-SNAPSHOT.el6.x86_64.rpm \
    ${PKG_URL}/cloudstack-awsapi-4.6.0-SNAPSHOT.el6.x86_64.rpm \
    ${PKG_URL}/cloudstack-management-4.6.0-SNAPSHOT.el6.x86_64.rpm


